.SUFFIXES: .f90

FC = xlf90

FFLAGS = -O2 -qarch=auto -qsuffix=f=f90 -qmaxmem=-1

LINK = 

OBJS = kind_mod.o       \
       matrix_mod.o     \
       ions_mod.o       \
       options_mod.o    \
       charge_mod.o     \
       chgcar_mod.o     \
       cube_mod.o       \
       io_mod.o         \
       bader_mod.o      \
       voronoi_mod.o

%.o %.mod : %.f90
	$(FC) $(FFLAGS) -c $*.f90

bader: $(OBJS) main.o
	rm -f bader
	$(FC) $(LINK) main.o -o $@ $(OBJS)

dist: bader
	tar -cf bader_osx.tar bader
	gzip -9 bader_osx.tar

clean:
	rm -f *.o *.mod bader bader.tar.gz
