OBJS = MatrixM.o      \
       ChargeIOM.o    \
       ChargeM.o      \
       Charge.o

charge: $(OBJS)
	$(FC) $(LINK) --out $@ $(OBJS) 
       
.SUFFIXES: .f90 .o

.f90.o:
	$(FC) $(LINK) $(FFLAGS) -c $*.f90

FC = lf95

#FFLAGS = --ap --chkglobal --xref --pca --nsav --trace --f95 --wo --warn --info
FFLAGS = --nap --nchk -O --npca --nsav --ntrace

#LINK = -L/home/andri/vinna/fcodes/lib -lfj9i6 -lfj9f6 -lelf
LINK = 

clean:
	rm -f *.o *.mod *.lst charge
