OBJS = MatrixM.o      \
       ChargeIOM.o    \
       ChargeM.o      \
       Charge.o

bader: $(OBJS)
	$(FC) $(LINK) -o $@ $(OBJS) 
       
.SUFFIXES: .f90 .o

.f90.o:
	$(FC) $(LINK) $(FFLAGS) -c $*.f90

FC = ifort

FFLAGS = -O2

LINK =  -static
#LINK = 

clean:
	rm -f *.o *.mod *.lst charge
